global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:3000']
  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:3001']
  - job_name: 'user-management-service'
    static_configs:
      - targets: ['user-management-service:3002']
  - job_name: 'medical-service'
    static_configs:
      - targets: ['medical-service:3003']
